from __future__ import annotations

from pathlib import Path

from mas.agents.architecture_agent import ArchitectureAgent
from mas.agents.evaluation_agent import EvaluationAgent
from mas.agents.implementation_agent import ImplementationAgent
from mas.agents.orchestrator_agent import OrchestratorAgent
from mas.agents.specification_agent import SpecificationAgent
from mas.agents.testing_agent import TestingAgent
from mas.models import BuildSummary


class MultiAgentBuilder:
    """Production-style orchestrated pipeline with iterative refinement loops."""

    def __init__(self) -> None:
        self.orchestrator = OrchestratorAgent(max_retries=2)
        self.spec_agent = SpecificationAgent()
        self.arch_agent = ArchitectureAgent()
        self.impl_agent = ImplementationAgent()
        self.test_agent = TestingAgent()
        self.eval_agent = EvaluationAgent()

    def build(self, idea: str, output_dir: Path | None = None) -> BuildSummary:
        output_dir = output_dir or Path("build_outputs")
        output_dir.mkdir(parents=True, exist_ok=True)
        milestones = self.orchestrator.make_milestones()

        planning = milestones[0]
        spec = self.orchestrator.run_stage(planning, lambda: self.spec_agent.generate(idea))

        architecture_ms = milestones[1]
        architecture = self.orchestrator.run_stage(architecture_ms, lambda: self.arch_agent.design(spec))

        iteration = 0
        while True:
            iteration += 1
            self.orchestrator.log("loop", f"starting iteration {iteration}")

            impl_ms = milestones[2]
            artifact = self.orchestrator.run_stage(
                impl_ms,
                lambda: self.impl_agent.generate(spec, architecture, output_dir / f"iteration_{iteration}"),
            )

            test_ms = milestones[3]
            tests = self.orchestrator.run_stage(test_ms, lambda: self.test_agent.validate(artifact))

            if not tests.passed and iteration <= self.orchestrator.max_retries:
                self.orchestrator.log("testing", "tests failed; retrying implementation", level="WARNING")
                continue

            eval_ms = milestones[4]
            evaluation = self.orchestrator.run_stage(eval_ms, lambda: self.eval_agent.evaluate(artifact, tests))

            if evaluation.architecture_issues and iteration <= self.orchestrator.max_retries:
                self.orchestrator.log(
                    "evaluation",
                    "architecture issues found; returning to planning layer",
                    level="WARNING",
                    issues=evaluation.architecture_issues,
                )
                spec = self.spec_agent.generate(f"{idea} (refined iteration {iteration})")
                architecture = self.arch_agent.design(spec)
                continue
            break

        return BuildSummary(
            idea=idea,
            milestones=milestones,
            iterations=iteration,
            test_report=tests,
            evaluation_report=evaluation,
            logs=self.orchestrator.logs,
            technical_debt=[
                "No CI/CD workflow generated by prototype",
                "Test coverage metrics are not instrumented",
            ],
            roadmap=[
                "Add deployment manifests and automated quality gates",
                "Add LLM-driven requirement gap detection with human approval checkpoints",
                "Split orchestration into event-driven workers for horizontal scaling",
            ],
        )
